Vagrant.configure(2) do |config|
  config.vm.box = "terrywang/archlinux"
  config.vm.provision :shell, path: "configure", privileged: false
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
end
