version: '2'
services:
    web-test:
        build: .
        environment:
            AC_MONGO_HOST: mongodb
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        links:
            - mongodb
        command: ["npm", "test"]
    mongodb:
        image: "mongo"
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
